name: Revert to Previous State

on:
  workflow_dispatch:

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Reset to specific commit
        run: |
          git reset --hard f65b47ba69bc4d9d60185c57e65ac92a5e8dbbf4
          git push -f origin main
